version: "3.8"
services:
  frontend:
    build:
      context: ./beautybook
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend-beautybook
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=beautybook_db
      - DB_USERNAME=myadmin
      - DB_PASSWORD=1234
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=beautybook_db
      - MYSQL_USER=myadmin
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
